version: "3.2"
services:
  php:
    build:
      context: .
    image: killerproc/php-mysql-demo  
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql-app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345
      - MYSQL_DB=demo_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:80"
    container_name: php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=demo_db
    container_name: mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin-app
networks:
  frontend:
  backend:
